service: serverless-patterns-include

plugins:
  - serverless-offline
  - serverless-plugin-typescript

package:
  patterns:
    - ./src/openapi-doc.yaml
#  include:
#    - ./src/openapi-doc.yaml

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  versionFunctions: false
  timeout: 3
  memorySize: 128

functions:
  helloTest:
    handler: src/hello.handler
    events:
      - http:
          method: GET
          path: /
